CREATE TABLE users (
	`id` CHAR(32) NOT NULL PRIMARY KEY,
	`name` VARCHAR(255),
	`enabled` TINYINT(1)
) ENGINE=INNODB;

CREATE TABLE sessions (
	FOREIGN KEY (user_id) REFERENCES users(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	`id` BINARY(16) NOT NULL PRIMARY KEY,
	`start_time` BIGINT NOT NULL,
	`end_time` BIGINT NOT NULL,
	`session_time` BIGINT NOT NULL
) ENGINE=INNODB;

CREATE TABLE data_single (
	FOREIGN KEY (session_id) REFERENCES sessions(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	`id` VARCHAR(255) KEY NOT NULL,
	`value` TEXT NOT NULL,
	`timestamp` BIGINT KEY NOT NULL
) ENGINE=INNODB;

CREATE TABLE data_array (
	FOREIGN KEY (session_id) REFERENCES sessions(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	`id` VARCHAR(255) KEY NOT NULL,
	`array_index` INT NOT NULL,
	`value` TEXT NOT NULL,
	`timestamp` BIGINT KEY NOT NULL,
) ENGINE=INNODB;